server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/meisallcom/config-repo
          username: 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
          password:
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
          skipSslValidation: true
          #proxy: http://127.0.0.1:51837
          proxy:
            http:
              host: 127.0.0.1
              port: '51837'
